User.create!([
  {email: "alice@example.com", password: "12341234", password_confirmation: "12341234", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 22, current_sign_in_at: "2015-12-08 23:56:54", last_sign_in_at: "2015-12-08 23:55:51", current_sign_in_ip: "::1", last_sign_in_ip: "::1", username: "alice"},
  {email: "bob@example.com", password: "12341234", password_confirmation: "12341234", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 23, current_sign_in_at: "2015-12-09 00:16:00", last_sign_in_at: "2015-12-09 00:12:55", current_sign_in_ip: "::1", last_sign_in_ip: "::1", username: "bob"},
  {email: "carol@example.com", password: "12341234", password_confirmation: "12341234", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 17, current_sign_in_at: "2015-12-09 00:14:19", last_sign_in_at: "2015-12-08 23:56:24", current_sign_in_ip: "::1", last_sign_in_ip: "::1", username: "carol"},
  {email: "matias@example.com", password: "12341234", password_confirmation: "12341234", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2015-12-09 00:15:13", last_sign_in_at: "2015-12-08 23:56:10", current_sign_in_ip: "::1", last_sign_in_ip: "::1", username: "matias"},
  {email: "dani@example.com", password: "12341234", password_confirmation: "12341234", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2015-12-08 23:50:46", last_sign_in_at: "2015-12-08 23:25:55", current_sign_in_ip: "::1", last_sign_in_ip: "::1", username: "Daniela"},
  {email: "echo@example.com", password: "12341234", password_confirmation: "12341234", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2015-12-08 23:40:48", last_sign_in_at: "2015-12-08 23:26:40", current_sign_in_ip: "::1", last_sign_in_ip: "::1", username: "Echo"}
])
Author.create!([
  {author_name: "Andrew S. Tanenbaum"},
  {author_name: "David Wetherall"},
  {author_name: "Philip Kotler"},
  {author_name: "Kevin Lane Keller"},
  {author_name: "Peter Eric Rossi"},
  {author_name: "Greg Martin Allenby"},
  {author_name: "Robert Edward McCulloch"},
  {author_name: "Paulo Coelho"},
  {author_name: "Luís M. B. Cabral"},
  {author_name: "Chris Pine"},
  {author_name: "Daniel Kahneman"},
  {author_name: "Avinash K. Dixit"},
  {author_name: "Barry Nalebuff"},
  {author_name: "Edward P. Lazear"},
  {author_name: "Mike Gibbs"},
  {author_name: "David Besanko"},
  {author_name: "Ronald Braeutigam"},
  {author_name: "David P. Baron"},
  {author_name: "Christopher Laszlo"},
  {author_name: "Jon Duckett"},
  {author_name: "Alex Kane"},
  {author_name: "Alan Marcus"},
  {author_name: "Zvi Bodie"},
  {author_name: "Mark Grinblatt"},
  {author_name: "Sheridan Titman"}
])
Book.create!([
  {description: "The past decade has seen a dramatic increase in the use of Bayesian methods in marketing due, in part, to computational and modelling breakthroughs, making its implementation ideal for many marketing problems. Bayesian analyses can now be conducted over a wide range of marketing problems, from new product introduction to pricing, and with a wide variety of different data sources. Bayesian Statistics and Marketing describes the basic advantages of the Bayesian approach, detailing the nature of the computational revolution. Examples contained include household and consumer panel data on product purchases and survey data, demand models based on micro-economic theory and random effect models used to pool data among respondents. The book also discusses the theory and practical use of MCMC methods. * Written by the leading experts in the field, this unique book: * Presents a unified treatment of Bayesian methods in marketing, with common notation and algorithms for estimating the models. * Provides a self-contained introduction to Bayesian methods. * Includes case studies drawn from the authors’ recent research to illustrate how Bayesian methods can be extended to apply to many important marketing problems. * Is accompanied by an R package, bayesm, which implements all of the models and methods in the book and includes many datasets. In addition the book’s website hosts datasets and R code for the case studies.", publisher: "John Wiley & Sons Inc", isbn13: "9780470863671", artwork: "http://books.google.com/books/content?id=nZFFAAAAYAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", subject_id: 317, year: "2005", title: "Bayesian statistics and marketing", isbn10: "0470863676"},
  {description: "\"My heart is afraid that it will have to suffer,\" the boy told the alchemist one night as they looked up at the moonless sky.\" Tell your heart that the fear of suffering is worse than the suffering itself. And that no heart has ever suffered when it goes in search of its dreams.\" Every few decades a book is published that changes the lives of its readers forever. The Alchemist is such a book. With over a million and a half copies sold around the world, The Alchemist has already established itself as a modern classic, universally admired. Paulo Coelho's charming fable, now available in English for the first time, will enchant and inspire an even wider audience of readers for generations to come. The Alchemist is the magical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure as extravagant as any ever found. From his home in Spain he journeys to the markets of Tangiers and across the Egyptian desert to a fateful encounter with the alchemist. The story of the treasures Santiago finds along the way teaches us, as only a few stories have done, about the essential wisdom of listening to our hearts, learning to read the omens strewn along life's path, and, above all, following our dreams.", publisher: "Harper Collins", isbn13: "9780061122415", artwork: "http://books.google.com/books/content?id=pTr44Sx6oWQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", subject_id: 319, year: "2006-04-25", title: "The Alchemist", isbn10: "0061122416"},
  {description: "This book provides an issue-driven introduction to industrial organization.", publisher: "MIT Press", isbn13: "9780262032865", artwork: "http://books.google.com/books/content?id=1diOmC8t0fgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", subject_id: 318, year: "2000", title: "Introduction to Industrial Organization", isbn10: "0262032864"},
  {description: "ALERT: Before you purchase, check with your instructor or review your course syllabus to ensure that you select the correct ISBN. Several versions of Pearson's MyLab & Mastering products exist for each title, including customized versions for individual schools, and registrations are not transferable. In addition, you may need a CourseID, provided by your instructor, to register for and use Pearson's MyLab & Mastering products. Packages Access codes for Pearson's MyLab & Mastering products may not be included when purchasing or renting from companies other than Pearson; check with the seller before completing your purchase. Used or rental books If you rent or purchase a used book with an access code, the access code may have been redeemed previously and you may have to purchase a new access code. Access codes Access codes that are purchased from sellers other than Pearson carry a higher risk of being either the wrong ISBN or a previously redeemed code. Check with the seller prior to purchase. -- Stay on the cutting-edge with the gold standard text that reflects the latest in marketing theory and practice. Marketing Management is the gold standard marketing text because its content and organization consistently reflect the latest changes in today's marketing theory and practice. Remaining true to its gold-standard status, the fourteenth edition includes an overhaul of new material and updated information, and now is available with mymarketinglab-Pearson's online tutorial and assessment platform. 0133764044 / 9780133764048 Marketing Management Plus 2014 MyMarketingLab with Pearson eText -- Access Card Package Package consists of: 0132102927 / 9780132102926 Marketing Management 0133766721 / 9780133766721 2014 MyMarketingLab with Pearson eText -- Access Card -- for Marketing Management", publisher: "Pearson College Division", isbn13: "9780132102926", artwork: "http://books.google.com/books/content?id=OYjntgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", subject_id: 260, year: "2012", title: "Marketing Management", isbn10: "0132102927"},
  {description: "Provides instructions for writing programs using the Ruby programming language.", publisher: "", isbn13: "9781934356364", artwork: "http://books.google.com/books/content?id=BRNEPwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", subject_id: 255, year: "2009", title: "Learn to Program", isbn10: "1934356360"},
  {description: "Major New York Times bestseller Winner of the National Academy of Sciences Best Book Award in 2012 Selected by the New York Times Book Review as one of the best books of 2011 A Globe and Mail Best Books of the Year 2011 Title One of The Economist's 2011 Books of the Year One of The Wall Street Journal's Best Nonfiction Books of the Year 2011 2013 Presidential Medal of Freedom Recipient In the international bestseller, Thinking, Fast and Slow, Daniel Kahneman, the renowned psychologist and winner of the Nobel Prize in Economics, takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think. System 1 is fast, intuitive, and emotional; System 2 is slower, more deliberative, and more logical. The impact of overconfidence on corporate strategies, the difficulties of predicting what will make us happy in the future, the profound effect of cognitive biases on everything from playing the stock market to planning our next vacation—each of these can be understood only by knowing how the two systems shape our judgments and decisions. Engaging the reader in a lively conversation about how we think, Kahneman reveals where we can and cannot trust our intuitions and how we can tap into the benefits of slow thinking. He offers practical and enlightening insights into how choices are made in both our business and our personal lives—and how we can use different techniques to guard against the mental glitches that often get us into trouble. Winner of the National Academy of Sciences Best Book Award and the Los Angeles Times Book Prize and selected by The New York Times Book Review as one of the ten best books of 2011, Thinking, Fast and Slow is destined to be a classic.", publisher: "Macmillan", isbn13: "9781429969352", artwork: "http://books.google.com/books/content?id=ZuKTvERuPG8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", subject_id: 277, year: "2011-10-25", title: "Thinking, Fast and Slow", isbn10: "1429969350"},
  {description: "The authors of Thinking Strategically demonstrate how to apply the principles in game theory to achieve greater personal and professional successes, drawing on a diverse array of case studies to explain how to develop a win-oriented way of seeing the world.", publisher: "W. W. Norton", isbn13: "9780393337174", artwork: "http://books.google.com/books/content?id=yDiJmAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", subject_id: 318, year: "2009-12-22", title: "The Art of Strategy", isbn10: "0393337170"},
  {description: "Personnel Economics in Practice, 3rd Edition by Edward Lazear and Michael Gibbs gives readers a rigorous framework for understanding organizational design and the management of employees. Economics has proven to be a powerful approach in the changing study of organizations and human resources by adding rigor and structure and clarifying many important issues. Not only will readers learn and apply ideas from microeconomics, they will also learn principles that will be valuable in their future careers.", publisher: "John Wiley & Sons", isbn13: "9781118206720", artwork: "http://books.google.com/books/content?id=cN_hBQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", subject_id: 180, year: "2014-11-03", title: "Personnel Economics in Practice", isbn10: "111820672X"},
  {description: "Business professionals that struggle to understand key concepts in economics and how they are applied in the field rely on Microeconomics. The 5th edition makes the material accessible while helping them build their problem-solving skills. It includes numerous new practice problems and exercises that arm them with a deeper understanding. Learning by Doing exercises explore the theories while boosting overall math skills. Graphs are included throughout the mathematical discussions to reinforce the material. In addition, the balanced approach of rigorous economics gives business professionals a more practical resource.", publisher: "Wiley", isbn13: "9781118572276", artwork: "http://books.google.com/books/content?id=4fmjmgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", subject_id: 178, year: "2013-11-18", title: "Microeconomics", isbn10: "1118572270"},
  {description: "Businesses compete in many ways, including nonmarket areas like corporate responsibility. Learn how to sharpen your firm's competitive edge. Baron's integrated approach combines the disciplines of economics, political science, law, and ethics to provide a deeper understanding of the managerial issues that arise in the business landscape. The seventh edition includes four new chapters on financial markets and their regulation, the investor's perspective and renewable power, the political economy of India, and behavioral ethics. The book also includes 26 new cases on timely topics.", publisher: "Prentice Hall", isbn13: "9780132620550", artwork: "http://books.google.com/books/content?id=a7oULgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", subject_id: 185, year: "2013", title: "Business and Its Environment", isbn10: "0132620553"},
  {description: "Provides information on how to make more interactive, engaging, and usable Web pages with JavaScript and jQuery, covering core programming concepts in both and such techniques as animation, form validation, and interactive galleries.", publisher: "John Wiley & Sons", isbn13: "9781118531648", artwork: "http://books.google.com/books/content?id=LpctBAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", subject_id: 255, year: "2014-06-30", title: "JavaScript and JQuery", isbn10: "1118531647"},
  {description: "The integrated solutions for Bodie, Kane, and Marcus’ Investments set the standard for graduate/MBA investments textbooks. The unifying theme is that security markets are nearly efficient, meaning that most securities are priced appropriately given their risk and return attributes. The content places greater emphasis on asset allocation and offers a much broader and deeper treatment of futures, options, and other derivative security markets than most investment texts. McGraw-Hill’s adaptive learning component, LearnSmart, provides assignable modules that help students master chapter core concepts and come to class more prepared. In addition, resources within Connect help students solve financial problems and apply what they’ve learned. Bodie Investments’ blend of practical and theoretical coverage combines with a complete digital solution to help your students achieve higher outcomes in the course.", publisher: "McGraw-Hill Education", isbn13: "9781259162794", artwork: "http://books.google.com/books/content?id=UzwmngEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", subject_id: 227, year: "2013-05-28", title: "Loose Leaf Investments with Connect Access Card", isbn10: "1259162796"}
])

Book.all.each do |bk|
  bk.subject_id = bk.subject_id - 165
  bk.save
end


Bookauthor.create!([
  {author_id: "5" ,  book_id: "1" },
  {author_id: "6" , book_id: "1" },
  {author_id: "7" , book_id: "1" },
  {author_id: "8" , book_id: "2" },
  {author_id: "9" , book_id: "3" },
  {author_id: "3" ,  book_id: "4" },
  {author_id: "4" ,  book_id: "4" },
  {author_id: "10", book_id: "5" },
  {author_id: "11", book_id: "6" },
  {author_id: "12", book_id: "7" },
  {author_id: "13", book_id: "7" },
  {author_id: "14", book_id: "8" },
  {author_id: "15", book_id: "8" },
  {author_id: "16", book_id: "9" },
  {author_id: "17", book_id: "9" },
  {author_id: "18", book_id: "10"},
  {author_id: "20", book_id: "11"},
  {author_id: "21", book_id: "12"},
  {author_id: "22", book_id: "12"},
  {author_id: "23", book_id: "12"}
])
Interest.create!([
  {status_id: "3", prop_price: "30.0", user_id: 3, listing_id: 9 },
  {status_id: "3", prop_price: "5.0", user_id: 3,  listing_id: 12},
  {status_id: "3", prop_price: "10.0", user_id: 3, listing_id: 11},
  {status_id: "6", prop_price: "100.0", user_id: 3,listing_id: 18},
  {status_id: "4", prop_price: "2.0", user_id: 3,  listing_id: 19},
  {status_id: "5", prop_price: "23.0", user_id: 1, listing_id: 20},
  {status_id: "3", prop_price: "33.0", user_id: 4, listing_id: 20}
])
Listing.create!([
  {status_id: "1", price: "100.0", sale_rent: "Sale", user_id: 6, book_id: 5 },
  {status_id: "1", price: "10.0", sale_rent: "Rent", user_id: 6,  book_id: 5 },
  {status_id: "1", price: "100.0", sale_rent: "Sale", user_id: 6, book_id: 7 },
  {status_id: "1", price: "15.0", sale_rent: "Rent", user_id: 6,  book_id: 7 },
  {status_id: "1", price: "200.0", sale_rent: "Sale", user_id: 6, book_id: 4 },
  {status_id: "1", price: "25.0", sale_rent: "Rent", user_id: 6,  book_id: 4 },
  {status_id: "1", price: "30.0", sale_rent: "Sale", user_id: 6,  book_id: 2 },
  {status_id: "1", price: "15.0", sale_rent: "Rent", user_id: 6,  book_id: 2 },
  {status_id: "1", price: "40.0", sale_rent: "Sale", user_id: 1,  book_id: 5 },
  {status_id: "1", price: "9.0", sale_rent: "Rent", user_id: 1,   book_id: 5 },
  {status_id: "1", price: "30.0", sale_rent: "Sale", user_id: 1,  book_id: 7 },
  {status_id: "1", price: "5.0", sale_rent: "Rent", user_id: 1,   book_id: 7 },
  {status_id: "2", price: "250.0", sale_rent: "Sale", user_id: 3, book_id: 12},
  {status_id: "1", price: "35.0", sale_rent: "Rent", user_id: 3,  book_id: 12},
  {status_id: "1", price: "200.0", sale_rent: "Sale", user_id: 3, book_id: 12},
  {status_id: "1", price: "14.0", sale_rent: "Sale", user_id: 3,  book_id: 1 },
  {status_id: "1", price: "150.0", sale_rent: "Sale", user_id: 5, book_id: 12},
  {status_id: "1", price: "123.0", sale_rent: "Sale", user_id: 1, book_id: 9 },
  {status_id: "1", price: "12.0", sale_rent: "Rent", user_id: 1,  book_id: 3 },
  {status_id: "1", price: "43.0", sale_rent: "Sale", user_id: 3,  book_id: 11}
])
Status.create!([
  {status: "active"},
  {status: "inactive"},
  {status: "submitted"},
  {status: "accepted"},
  {status: "declined"},
  {status: "rented"},
  {status: "finalized"},
  {status: "given up"},
  {status: "listing deleted"},
  {status: "expired"},
  {status: "dismissed"}
])
Subject.create!([
  {subject_number: "30000", subject_name: "Financial Accounting"},
  {subject_number: "30001", subject_name: "Cost Analysis and Internal Controls"},
  {subject_number: "30116", subject_name: "Accounting and Financial Analysis I"},
  {subject_number: "30118", subject_name: "Taxes and Business Strategy"},
  {subject_number: "30130", subject_name: "Financial Statement Analysis"},
  {subject_number: "30600", subject_name: "Workshop in Accounting Research"},
  {subject_number: "30901", subject_name: "Economic Modeling of Accounting Issues"},
  {subject_number: "30902", subject_name: "Empirical Research in Accounting"},
  {subject_number: "30903", subject_name: "Topics in Empirical Accounting Research"},
  {subject_number: "30904", subject_name: "Empirical Research on Managers Corporate Financial Reporting Decisions"},
  {subject_number: "31702", subject_name: "Leadership Effectiveness and Development (LEAD) Lab II"},
  {subject_number: "31710", subject_name: "Kapnick Initiative Leadership Effectiveness and Development Lab"},
  {subject_number: "33001", subject_name: "Microeconomics"},
  {subject_number: "33002", subject_name: "Accelerated Microeconomics"},
  {subject_number: "33032", subject_name: "Managing the Workplace"},
  {subject_number: "33040", subject_name: "Macroeconomics"},
  {subject_number: "33101", subject_name: "Advanced Microeconomic Analysis"},
  {subject_number: "33112", subject_name: "Business in Historical Perspective"},
  {subject_number: "33222", subject_name: "Sports Analytics"},
  {subject_number: "33305", subject_name: "The Firm and the Non-Market Environment"},
  {subject_number: "33310", subject_name: "Employment Law for Entrepreneurs & Managers"},
  {subject_number: "33401", subject_name: "Money and Banking"},
  {subject_number: "33402", subject_name: "Understanding Central Banks"},
  {subject_number: "33450", subject_name: "Real Estate Investments I"},
  {subject_number: "33451", subject_name: "Real Estate Investments II"},
  {subject_number: "33471", subject_name: "Business, Politics, and Ethics"},
  {subject_number: "33501", subject_name: "International Commercial Policy"},
  {subject_number: "33502", subject_name: "International Financial Policy"},
  {subject_number: "33503", subject_name: "Managing the Firm in the Global Economy"},
  {subject_number: "33520", subject_name: "The Wealth of Nations"},
  {subject_number: "33610", subject_name: "Applied Economics Workshop"},
  {subject_number: "33650", subject_name: "Workshop in Macro and International Economics"},
  {subject_number: "33660", subject_name: "Practical Computing for Economists: Colloquium"},
  {subject_number: "33701", subject_name: "Energy Policy Practicum: Alternative Transportation Fuels"},
  {subject_number: "33902", subject_name: "Numerical Methods in Economics"},
  {subject_number: "33911", subject_name: "The Economics of Information"},
  {subject_number: "33915", subject_name: "Market Design"},
  {subject_number: "33921", subject_name: "Advanced Industrial Organization I"},
  {subject_number: "33922", subject_name: "Advanced Industrial Organization II"},
  {subject_number: "33923", subject_name: "Advanced Industrial Organization III"},
  {subject_number: "33946", subject_name: "International Macroeconomics and Trade"},
  {subject_number: "33948", subject_name: "Financial Markets in the Macroeconomy"},
  {subject_number: "33949", subject_name: "Applied Macroeconomics: Heterogeneity and Macro"},
  {subject_number: "34101", subject_name: "Entrepreneurial Finance and Private Equity"},
  {subject_number: "34102", subject_name: "New Venture Strategy"},
  {subject_number: "34103", subject_name: "Building the New Venture"},
  {subject_number: "34104", subject_name: "Special Topics in Entrepreneurship: Developing a New Venture (New Venture Challenge)"},
  {subject_number: "34105", subject_name: "Cases in Entrepreneurship Seminar"},
  {subject_number: "34106", subject_name: "Commercializing Innovation: Tools to Research and Analyze Private Enterprises"},
  {subject_number: "34110", subject_name: "Social Enterprise Lab"},
  {subject_number: "34111", subject_name: "Entrepreneurial Selling"},
  {subject_number: "34115", subject_name: "New Social Ventures"},
  {subject_number: "34302", subject_name: "Entrepreneurship through Acquisition"},
  {subject_number: "34303", subject_name: "Mergers and Acquisitions: Legal Perspectives"},
  {subject_number: "34701", subject_name: "New Venture and Small Enterprise Lab"},
  {subject_number: "34704", subject_name: "Real Estate Lab: Real Estate Challenge"},
  {subject_number: "34705", subject_name: "Entrepreneurial Discovery"},
  {subject_number: "34706", subject_name: "Energy and CleanTech Lab"},
  {subject_number: "34707", subject_name: "Private Equity Lab"},
  {subject_number: "34708", subject_name: "Venture Capital Lab"},
  {subject_number: "34721", subject_name: "Global Social Impact Practicum"},
  {subject_number: "35000", subject_name: "Investments"},
  {subject_number: "35001", subject_name: "Introductory Finance"},
  {subject_number: "35100", subject_name: "Financial Instruments"},
  {subject_number: "35101", subject_name: "Futures, Forwards, Options & Swaps: Theory and Practice"},
  {subject_number: "35105", subject_name: "History of Financial Thought and Practice"},
  {subject_number: "35120", subject_name: "Portfolio Management"},
  {subject_number: "35121", subject_name: "Behavioral Finance"},
  {subject_number: "35122", subject_name: "Hedge Fund Investing"},
  {subject_number: "35125", subject_name: "Quantimental Investment"},
  {subject_number: "35130", subject_name: "Fixed Income Asset Pricing"},
  {subject_number: "35131", subject_name: "Cases in Financial Risk Management"},
  {subject_number: "35140", subject_name: "Wealth and Family Enterprise Management"},
  {subject_number: "35200", subject_name: "Corporation Finance"},
  {subject_number: "35201", subject_name: "Cases in Financial Management"},
  {subject_number: "35206", subject_name: "Advanced Topics in Corporate Finance"},
  {subject_number: "35211", subject_name: "The Analytics of Financial Crises"},
  {subject_number: "35215", subject_name: "Behavioral and Institutional Finance"},
  {subject_number: "35600", subject_name: "Seminar: Finance"},
  {subject_number: "35601", subject_name: "Applied Theory Workshop"},
  {subject_number: "35901", subject_name: "Theory of Financial Decisions I"},
  {subject_number: "35902", subject_name: "Theory of Financial Decisions II"},
  {subject_number: "35903", subject_name: "Theory of Financial Decisions III"},
  {subject_number: "35905", subject_name: "Topics in Empirical Finance"},
  {subject_number: "35907", subject_name: "Topics in Asset Pricing"},
  {subject_number: "35908", subject_name: "Research Projects: Finance"},
  {subject_number: "35912", subject_name: "Asset Pricing"},
  {subject_number: "35915", subject_name: "International Macroeconomics and Finance"},
  {subject_number: "36106", subject_name: "Managerial Decision Modeling"},
  {subject_number: "36110", subject_name: "Application Development"},
  {subject_number: "36600", subject_name: "Workshop in Operations/Management Science"},
  {subject_number: "36905", subject_name: "Approximate Dynamic Programming"},
  {subject_number: "36906", subject_name: "Stochastic Processes"},
  {subject_number: "36907", subject_name: "Networks I: Introduction to Modeling and Analysis ?"},
  {subject_number: "37000", subject_name: "Marketing Strategy"},
  {subject_number: "37101", subject_name: "Consumer Behavior"},
  {subject_number: "37103", subject_name: "Data-Driven Marketing"},
  {subject_number: "37106", subject_name: "Marketing Research"},
  {subject_number: "37200", subject_name: "New Products and Services"},
  {subject_number: "37201", subject_name: "Lab in Developing New Products and Services"},
  {subject_number: "37202", subject_name: "Pricing Strategies"},
  {subject_number: "37205", subject_name: "Going to Market: Managing Channel Strategy"},
  {subject_number: "37301", subject_name: "Digital Marketing"},
  {subject_number: "37304", subject_name: "Digital and Algorithmic Marketing"},
  {subject_number: "37601", subject_name: "Marketing Workshop"},
  {subject_number: "37701", subject_name: "Laboratory in New Product and Strategy Development I"},
  {subject_number: "37902", subject_name: "Foundations of Advanced Quantitative Marketing"},
  {subject_number: "37903", subject_name: "Adv Mktg Theory: Behavioral Science Approach"},
  {subject_number: "37904", subject_name: "Advanced Quantitative Marketing"},
  {subject_number: "37905", subject_name: "Marketing Literature Seminar"},
  {subject_number: "38001", subject_name: "Managing in Organizations"},
  {subject_number: "38002", subject_name: "Managerial Decision Making"},
  {subject_number: "38003", subject_name: "Power and Influence in Organizations"},
  {subject_number: "38101", subject_name: "Persuasion: Effective Business Communication ?"},
  {subject_number: "38103", subject_name: "Strategies and Processes of Negotiation"},
  {subject_number: "38105", subject_name: "Advanced Negotiations"},
  {subject_number: "38115", subject_name: "Ethics of Business"},
  {subject_number: "38116", subject_name: "Leading and Managing Teams"},
  {subject_number: "38119", subject_name: "Designing a Good Life"},
  {subject_number: "38601", subject_name: "Workshop in Behavioral Science"},
  {subject_number: "38902", subject_name: "Current Topics in Behavioral Science II"},
  {subject_number: "38903", subject_name: "Current Topics in Behavioral Science III"},
  {subject_number: "38912", subject_name: "Behavioral Economics"},
  {subject_number: "38913", subject_name: "Foundations of Judgment and Decision Making"},
  {subject_number: "39001", subject_name: "Strategy and Structure: Markets and Organizations"},
  {subject_number: "39002", subject_name: "Strategic Leadership"},
  {subject_number: "39005", subject_name: "Strategic Leadership in Management Networks ?"},
  {subject_number: "39006", subject_name: "Advanced Topics in Management Networks ?"},
  {subject_number: "39101", subject_name: "Technology Strategy"},
  {subject_number: "39600", subject_name: "Workshop in Organizations and Markets"},
  {subject_number: "40000", subject_name: "Operations Management: Business Process Fundamentals"},
  {subject_number: "40101", subject_name: "Supply Chain Strategy and Practice"},
  {subject_number: "40108", subject_name: "Revenue Management"},
  {subject_number: "40110", subject_name: "Managing Service Operations"},
  {subject_number: "40111", subject_name: "Project Management"},
  {subject_number: "40201", subject_name: "Healthcare Analytics ?"},
  {subject_number: "40721", subject_name: "Healthcare Analytics Lab"},
  {subject_number: "40904", subject_name: "Inventory Theory and Supply Chain Management ?"},
  {subject_number: "41000", subject_name: "Business Statistics"},
  {subject_number: "41100", subject_name: "Applied Regression Analysis"},
  {subject_number: "41201", subject_name: "Big Data"},
  {subject_number: "41202", subject_name: "Analysis of Financial Time Series"},
  {subject_number: "41203", subject_name: "Financial Econometrics"},
  {subject_number: "41204", subject_name: "Machine Learning"},
  {subject_number: "41301", subject_name: "Statistical Insight into Marketing, Consulting, and Entrepreneurship"},
  {subject_number: "41600", subject_name: "Econometrics and Statistics Colloquium"},
  {subject_number: "41901", subject_name: "Probability and Statistics"},
  {subject_number: "41902", subject_name: "Statistical Inference"},
  {subject_number: "41903", subject_name: "Applied Econometrics"},
  {subject_number: "41910", subject_name: "Time-series Analysis for Forecasting and Model Building"},
  {subject_number: "41912", subject_name: "Applied Multivariate Analysis"},
  {subject_number: "41913", subject_name: "Bayesian Inference"},
  {subject_number: "42001", subject_name: "Competitive Strategy"},
  {subject_number: "42002", subject_name: "Business Policy"},
  {subject_number: "42102", subject_name: "The Strategy Symposium"},
  {subject_number: "42108", subject_name: "Corporate Governance"},
  {subject_number: "42110", subject_name: "Strategic Investment Decisions"},
  {subject_number: "42116", subject_name: "Game Theory"},
  {subject_number: "42117", subject_name: "Platform Competition ?"},
  {subject_number: "42121", subject_name: "Merger & Acquisition Strategy"},
  {subject_number: "42122", subject_name: "Innovation Strategy"},
  {subject_number: "42123", subject_name: "Reputation, Regulation and Communications – How Media Influences Business"},
  {subject_number: "42201", subject_name: "The Legal Infrastructure of Business"},
  {subject_number: "42701", subject_name: "Strategy Lab"},
  {subject_number: "42703", subject_name: "Entrepreneurship: Urban Opportunities and Solutions"}
])
Wishlist.create!([
  {status_id: "1", price: "100.0", sale_rent: "Sale", user_id: 6, book_id: 12},
  {status_id: "1", price: "10.0", sale_rent: "Rent", user_id: 6, book_id: 12},
  {status_id: "1", price: "11.0", sale_rent: "Rent", user_id: 1, book_id: 12},
  {status_id: "1", price: "50.0", sale_rent: "Sale", user_id: 4, book_id: 12},
  {status_id: "1", price: "20.0", sale_rent: "Sale", user_id: 3, book_id: 3},
  {status_id: "1", price: "10.0", sale_rent: "Rent", user_id: 4, book_id: 3}
])
